version: 'latest'

services:
  mysql:
    image: mysql:latest
    container_name: conf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: conf_brsu
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "10.0.0.101"]
      timeout: 20s
      retries: 10

  server:
    build: ./
    container_name: conf-server
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      DB_HOST: mysql  
      DB_PORT: 3306
      DB_USER: rootuser
      DB_PASSWORD: rootpassword
      DB_NAME: conf_brsu
      PORT: 8888

volumes:
  mysql_data: